### ISSUE TITLE
Tenants not eating player randomly?

### ISSUE THREAD

**Issue by VelRoz** [Sheights/StarboundSimpleVoreMod#190]
I'm not sure if this is a bug or not but it seems like the special vore tenants don't eat me, only when I double tap 'E'. Instead they just come up to me and hearts come out. Am I supposed to do their quests in order for them to eat me?

**Comment by florancetheavian** [comment]
are you using the vore badges? and no you don't need to do their quests for them to eat you.

**Comment by VelRoz** [comment]
I do have the vore badges, and they spawn the correct tenants. The tenants are also able to eat other tenants, just that they don't eat me. I've already edited the config, changing the player chance value to 1 like the readme says, but nothing changed. I'm using the latest build from the masterbranch if that solves anything

**Comment by florancetheavian** [comment]
I'm not sure, as soon as it goes into the code of the mod, that's where my help becomes unhelpful. I hope you figure it out soon! sorry I'm unable to help with this much. I'm not sure what could be going on now since the tenants eat other tenants. they should be able to eat you as well... I'm not sure if you've tried but maybe "request" to be eaten by pressing E twice? if you've already tried that, then I'm not sure what's going on.

**Comment by florancetheavian** [comment]
sometimes double tapping E is the only way. it can take up to 2 minutes for my tenants to choose to eat me. that's if I follow them, and keep pestering them though.

**Comment by VelRoz** [comment]
Thanks for the help. I'll leave the issue open though. Maybe I just have bad luck

**Comment by florancetheavian** [comment]
anytime! sorry if you didn't figure it out, you're not alone in having bad luck occasionally.

**Comment by VelRoz** [comment]
Okay, after about a month of this not working, it got fixed after I loaded Starbound (32 bit) instead of the regular one, and now it works for both versions. I'm too tired to figure out why this worked so I'm just closing this I guess
