### ISSUE TITLE
Crafting

### ISSUE THREAD

**Issue by MaxShadowland** [Sheights/StarboundSimpleVoreMod#46]
Hello I seem to be having difficulty installing and/or utilizing the mod. None of the craftable items seem to be appearing and I was wondering if somebody could give me an in-depth explanation on how to fix this.

Thank you in advance!

**Comment by Sheights** [comment]
Hello!

As of 8.0 all content is accessible through the Food Hall, vore mall.
The Foodhall is accessible via the ancient portal, same way you get to the outpost.
The stores are no longer craft-able because we have such a neat place to put them now!
You may still purchase the holographic store from the furniture store at the Food Hall.
Please let me know if this solved your issue.

**Comment by MaxShadowland** [comment]
Yes it did fix the problem, thank you for the rapid and helpful response!
