### ISSUE TITLE
Bug: NPCs die as player gets deed reward

### ISSUE THREAD

**Issue by Deadmanovi4** [Sheights/StarboundSimpleVoreMod#90]
[Beware. English is not a primary language in my country. G.Translate incoming]

I was surprised when I noticed that my NPCs disappeared when I received the deed award, and the icon of the house became a red cross. By entering into the search for my problem, I found out that NPCs were simply dying. Unlike those on the forum, they did not die from what I said to them, just clickin on yellow deed colony.

Died like normal NPCs, and with this mod.
The error occurs in the line:
[15: 07: 59.409] [Error] Exception while invoking lua function 'update'. (LuaException) Error code 2, [string "/npcs/bmain.lua"]:166: (LuaException) Error code 2, [string" /scripts/tenant.lua"]:184: attempt to index a nil value (local 'Rent')
And in the reasons:
[String "/scripts/vore/npcvore.lua"]:226: in function <[string" /scripts/vore/npcvore.lua "]: 222>
And in this file string 222 is function update(dt)
The log itself is attached.
[[backup]starbound.log.txt](https://github.com/Sheights/StarboundSimpleVoreMod/files/999344/backup.starbound.log.txt)

The game is licensed, Steam. Tested on a stable and at night. The results are the same.
This is the only mod that is used in the game, and the mod is downloaded using Github Desktop.
Tried to restore the files and Steam really recovered 6 files, but this problem did not solve.

**Comment by Deadmanovi4** [comment]
upd: vanilla deed colony work correctly, compact still buggy

**Comment by lunapanshiel** [comment]
it's a dialogue issue, the NPC can't read the comment they're supposed to be making them, and the game's error handling method for that is just to kill the NPC causing the error

**Comment by Sheights** [comment]
That's wonderful you figured out the error!
Which NPC is missing the rent dialogue?

**Comment by lunapanshiel** [comment]
sorry i haven't really been able to mess with the mod as of late, been far too busy with other projects so i can't really provide much information as to who and what aside from one or more NPCs can't make sense of their rent dialogue. i'm just very familiar with that quirk.

if an NPC tries to say something, but cannot find -any- dialogue to use for it, including placeholder dialogue, the NPC just instantly dies.

with standard tenants you'll often see them repeatedly teleporting back to the deed as they can't fully "die" depending on what part of their dialogue broke... the cause is typically as simple as a comma in the wrong spot or missing, a missing quotation mark, too many quotation marks, ect.
